name: Prepare Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Exact version to release (e.g. 1.2.3). Leave empty to infer from commits.'
        required: false
        type: string

jobs:
  prepare:
    uses: holochain/actions/.github/workflows/nodejs-prepare-release.yml@v1.11.0
    with:
      cliff_config_url: 'https://raw.githubusercontent.com/holochain/release-integration/refs/heads/main/pre-1.0-cliff.toml'
      force_version: ${{ inputs.version }}
      package_manager: yarn
    secrets:
      GH_TOKEN: ${{ secrets.HRA2_GITHUB_TOKEN }}
